# render.yaml
services:
  - type: web
    name: career-ai-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SESSION_SECRET
        value: your_secret_key
