"""Add tailored_resume to users

Revision ID: c044e0d49ca2
Revises: d205da42b96f
Create Date: 2025-06-12 21:42:17.338171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c044e0d49ca2'
down_revision: Union[str, None] = 'd205da42b96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tailored_resume', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tailored_resume')
    # ### end Alembic commands ###
